### ISSUE TITLE
Base Class IEEEP370 not seen in ReadMeDocs

### ISSUE THREAD

**Issue by denzchoe** [mhuser/scikit-rf#7]
https://github.com/mhuser/scikit-rf/blob/4713f7720909d544264fe02cc973c16601c39d47/skrf/calibration/deembedding.py#L38-L52

Hi @mhuser ,

Quick glance, The new base class of P370 is not reflected on readmedocs, but it exist in your repo.

![image](https://github.com/user-attachments/assets/49651659-4cfc-45d0-842d-957912f999f9)

Is it because of this autosummary section not updated?

**Comment by mhuser** [comment]
Nice spotted, I should fix this!

**Comment by mhuser** [comment]
Done 😄
